#################
version: "2"
services:
        api:
                build: .
                restart: always
                volumes: 
                    - /app
                ports:
                        - "3000:3000"
